openai:
  api_url: "https://api.openai.com/v1/chat/completions"

# 24 hours x 60 minutes = 1440 minutes
jwt:
  algorithm: "HS256"
  access_token_expire_minutes: 1440
  verification_token_expire_minutes: 15

app:
  chat_history_length: 10
  default_ai_model: "gpt-4-1106-preview"
  welcome_message: "Welcome to SeanGPT! Your account is ready to go!"
  request_referral_message: "Please send your referral code as a standalone message."
  no_whatsapp_message: "Please only send SMS messages to this number. Whatsapp will be supported in the future."
  no_mms_message: "Please only send SMS messages to this number. Multimedia messages will be supported in the future."
  sms_opt_in_message: "You must opt-in to receive messages to use SeanGPT. Please reply 'AGREE' to this number to opt-in.\n\nTerms: https://sean-gpt.com/tos"
  ai_system_message: "You are a helpful AI assistant called SeanGPT that users interact with users via SMS. Therefore, your responses are preferred short and split into chunks with character count fewer than 160. When you want to go over this count, use a | character to separate messages. Break your response at reasonable, logical breaks. Do not include markup in your response. Match the user in terms of mood and style."
  max_sms_characters: 139
  phone_number: "+15104548054"
  phone_verification_message: "Your verification code is: {}"
  ws_token_timeout_seconds: 30

api:
  replicas: 1
  port: 8000