name: 'Sync Version from pyproject.toml'
description: 'Extracts version from pyproject.toml and sets it as an output'

inputs:
  pyproject-path:
    description: 'Relative path to the pyproject.toml file'
    required: true
    default: 'pyproject.toml'

outputs:
  version:
    description: 'The extracted version'

runs:
  using: 'composite'
  steps:
    - name: Setup Python environment
      uses: ./.github/actions/setup

    - name: Extract Version from pyproject.toml
      run: |
        version=$(poetry run python -c 'import toml; print(toml.load("${{ inputs.pyproject-path }}")["tool"]["poetry"]["version"])')
        echo "version=$version" >> $GITHUB_ENV
        echo "::set-output name=version::$version"
      shell: bash
