# Use the ubuntu base image
FROM python:3.10

# Copy in the requirements.txt file
COPY dist/requirements.txt .

# Install the requirements
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY alembic.ini /alembic.ini
COPY migrations /migrations