FROM nginx:1.25.3-alpine

# Copy the build output from React to the Nginx html directory
COPY sean_gpt_frontend/build /usr/share/nginx/html

# Copy the custom Nginx configuration file
COPY sean_gpt_frontend/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]