environments:
  prod:
    values:
    - config/values.yaml
    - config/production/values.yaml
    - config/production/secrets.yaml
    kubeContext: sean-gpt-aks
  local: &default
    values:
    - config/values.yaml
    - config/local/values.yaml
    - config/local/test_secrets.yaml
    kubeContext: kind-sean-gpt-local
  default: *default
---
# Rest of your Helmfile
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: kedacore
    url: https://kedacore.github.io/charts
  - name: milvus
    url: https://zilliztech.github.io/milvus-helm/
  - name: minio
    url: https://charts.min.io/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: jetstack
    url: https://charts.jetstack.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    installed: {{ eq .Environment.Values.env "prod" }}
    createNamespace: true
    namespace: ingress-nginx
    set:
      - name: controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"
        value: "/healthz"
# helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz

  - name: cert-manager
    chart: jetstack/cert-manager
    installed: {{ eq .Environment.Values.env "prod" }}
    createNamespace: true
    namespace: cert-manager
    set:
      - name: installCRDs
        value: true
# helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set installCRDs=true

  - name: milvus
    chart: milvus/milvus
    createNamespace: true
    namespace: milvus
    set:
    - name: cluster.enabled
      value: false
    - name: etcd.replicaCount
      value: 1
    - name: minio.mode
      value: standalone
    - name: minio.persistence.size
      value: 10Gi
    - name: pulsar.enabled
      value: false

  - name: minio
    chart: minio/minio
    createNamespace: true
    namespace: minio
    set:
    - name: mode
      value: standalone
    - name: replicas
      value: 1
    - name: resources.requests.memory
      value: 512Mi
    - name: persistence.size
      value: 10Gi
    - name: users[0].accessKey
      value: {{ .Environment.Values.minio.access_key | quote}}
    - name: users[0].secretKey
      value: {{ .Environment.Values.minio.secret_key | quote}}
    - name: users[0].policy
      value: readwrite

  - name: kafka
    chart: bitnami/kafka
    createNamespace: true
    namespace: kafka
    set:
    - name: listeners.client.protocol
      value: "PLAINTEXT"
    - name: sasl.interbroker.password
      value: {{ .Environment.Values.kafka.sasl.interbroker.password | quote}}
    - name: sasl.controller.password
      value: {{ .Environment.Values.kafka.sasl.controller.password | quote}}

  - name: keda
    chart: kedacore/keda
    createNamespace: true
    namespace: keda

  - name: kubernetes-dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard
    createNamespace: true
    namespace: kubernetes-dashboard
    # Access with:
    # $ kubectl proxy
    # http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

  - name: postgres
    chart: bitnami/postgresql
    createNamespace: true
    namespace: postgres
    set:
    - name: auth.database
      value: {{ .Environment.Values.database.name }}
    - name: auth.password
      value: {{ .Environment.Values.api_db_password }}
    - name: auth.username
      value: {{ .Environment.Values.api_db_user }}
    - name: primary.service.ports.postgresql
      value: {{ .Environment.Values.database.port }}

  - name: redis
    chart: bitnami/redis
    createNamespace: true
    namespace: redis
    set:
    - name: architecture
      value: standalone
    - name: auth.enabled
      value: false

  - name: grafana
    chart: grafana/grafana
    createNamespace: true
    namespace: monitoring
    set:
      - name: adminUser
        value: {{ .Environment.Values.grafana.adminUser }}
      - name: adminPassword
        value: {{ .Environment.Values.grafana.adminPassword }}
      - name: persistence.enabled
        value: true

  - name: prometheus
    chart: prometheus-community/prometheus
    createNamespace: true
    namespace: monitoring
    values:
    - extraScrapeConfigs: |
        - job_name: prometheus-postgres-exporter
          metrics_path: /metrics
          static_configs:
          - targets: ['postgres-exporter-prometheus-postgres-exporter.postgres.svc.cluster.local:80']

  - name: postgres-exporter
    chart: prometheus-community/prometheus-postgres-exporter
    namespace: postgres
    set:
      - name: config.datasource.host
        value: "postgres-postgresql.postgres.svc.cluster.local"
      - name: config.datasource.user
        value: {{ .Environment.Values.api_db_user }}
      - name: config.datasource.password
        value: {{ .Environment.Values.api_db_password }}
      - name: config.datasource.database
        value: {{ .Environment.Values.database.name }}

  - name: "seangpt"
    chart: "./sean_gpt_chart"
    createNamespace: true
    namespace: seangpt
    set:
    - name: environment
      value: {{ .Environment.Values.env }}
    - name: database.host
      value: "postgres-postgresql.postgres.svc.cluster.local"
    - name: redis.host
      value: "redis-master.redis.svc.cluster.local"
    - name: minio.host
      value: "minio.minio.svc.cluster.local"
    values:
    - {{ toYaml .Environment.Values | nindent 6}}