name: 'Setup Python environment'
description: 'Set up Python, pipx, and Poetry, and install dependencies'

inputs:
  python-version:
    description: 'Version of Python to set up'
    required: true
    default: '3.10'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up pipx
      run: |
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
      shell: bash

    - name: Install Poetry
      run: |
        pipx install poetry
      shell: bash

    - name: Install dependencies
      run: |
        poetry install
      shell: bash
