apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-upgrade
spec:
  template:
    spec:
      containers:
      - name: alembic-upgrade
        image: sean_gpt_migrate:latest
        command: ["alembic", "upgrade", "head"]
      restartPolicy: Never
  backoffLimit: 4