apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fastapi-backend
spec:
  replicas: 1  # Adjust replica count as needed
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
      - name: fastapi-backend
        image: sean_gpt_backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: fastapi-secrets
        - configMapRef:
            name: fastapi-env
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend
spec:
  type: ClusterIP
  selector:
    app: fastapi-backend
  ports:
    - port: 8000
      targetPort: 8000