seangpt:
  api_image:
    image_name: "ghcr.io/mrplants/sean_gpt_api"
    image_tag: "dev"

  migrate_image:
    image_name: "ghcr.io/mrplants/sean_gpt_migrate"
    image_tag: "dev"

  frontend_image:
    image_name: "ghcr.io/mrplants/sean_gpt_frontend"
    image_tag: "dev"

domain: "dev.sean-gpt.com"
api_domain: "api.dev.sean-gpt.com"
cert_prefix: "dev-sean-gpt"

env: dev