apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        envFrom:
        - secretRef:
            name: sean-gpt-db-secrets
        - configMapRef:
            name: sean-gpt-env
        env:
        - name: PGDATA
          value: /data/pgdata
        volumeMounts:
        - name: postgres-volume
          mountPath: /data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      volumes:
      - name: init-scripts
        configMap:
          name: postgres-init-script
  volumeClaimTemplates:
  - metadata:
      name: postgres-volume
    spec:
      storageClassName: standard # "standard" for kind, "default" for azure
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sh: |
    #!/bin/bash
    # Create a new user
    PGPASSWORD=$POSTGRES_PASSWORD psql -v ON_ERROR_STOP=1 -U $POSTGRES_USER -d postgres -c "CREATE USER $API_DB_USER WITH ENCRYPTED PASSWORD '$API_DB_PASSWORD';"

    # Create a new database
    PGPASSWORD=$POSTGRES_PASSWORD psql -v ON_ERROR_STOP=1 -U $POSTGRES_USER -d postgres -c "CREATE DATABASE $API_DB_NAME;"

    # Grant the user the ability to create tables in the public schema
    PGPASSWORD=$POSTGRES_PASSWORD psql -v ON_ERROR_STOP=1 -U $POSTGRES_USER -d $API_DB_NAME -c "
        GRANT CREATE ON SCHEMA public TO $API_DB_USER;
    "