# Database credentials
api_db_user: "api_user"
api_db_password: "TEST PASSWORD"

# API keys
openai_api_key: "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
captcha_secret_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
captcha_site_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Application-specific secrets
user_admin_phone: "+11234567890"
user_admin_password: "TEST PASSWORD"
# openssl rand -hex 32
jwt_secret_key: "7957dd0fe94a454044f502c7c2aad06256506919648d0c10ca47dda19998b95f"

# Other sensitive information
twilio_test_sid: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
twilio_test_auth_token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
twilio_sid: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
twilio_auth_token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

minio:
  access_key: "minioaccesskey2"
  secret_key: "miniosecretkey2"

grafana:
  adminUser: "admin"
  adminPassword: "TEST PASSWORD"

kafka:
  sasl:
    controller:
      password: "TEST PASSWORD"
    interbroker:
      password: "TEST PASSWORD"
  
rabbitmq:
  secret_password: "test_PASSWORD"
  secret_username: "default_user"
  secret_host: "file-processing-queue.seangpt.svc"
  secret_port: "5672"
  secret_type: "rabbitmq"
  secret_provider: "rabbitmq"
