"""file Processing status

Revision ID: f45eae420834
Revises: 5f932be40f12
Create Date: 2024-01-24 22:08:50.433081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f45eae420834'
down_revision: Union[str, None] = '5f932be40f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('textfilechunkingstatus',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('file_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('chunks_processed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_textfilechunkingstatus_file_id'), 'textfilechunkingstatus', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_textfilechunkingstatus_file_id'), table_name='textfilechunkingstatus')
    op.drop_table('textfilechunkingstatus')
    # ### end Alembic commands ###
