"""file_share_set_link

Revision ID: 313d46ffeb68
Revises: e7af328c15b7
Create Date: 2024-01-16 21:41:51.975976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '313d46ffeb68'
down_revision: Union[str, None] = 'e7af328c15b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filesharesetlink',
    sa.Column('file_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('share_set_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['share_set_id'], ['shareset.id'], ),
    sa.PrimaryKeyConstraint('file_id', 'share_set_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filesharesetlink')
    # ### end Alembic commands ###
