"""add sms opt-in

Revision ID: 8dbadb217ee4
Revises: 6676b56757aa
Create Date: 2024-01-11 23:46:28.630447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8dbadb217ee4'
down_revision: Union[str, None] = '6676b56757aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authenticateduser', sa.Column('opted_into_sms', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authenticateduser', 'opted_into_sms')
    # ### end Alembic commands ###
