"""Adding user opt-in for SMS

Revision ID: ac6b0d9be7c5
Revises: b555042d7e9d
Create Date: 2024-01-16 09:28:31.396541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac6b0d9be7c5'
down_revision: Union[str, None] = 'b555042d7e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authenticateduser', sa.Column('opted_into_sms', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authenticateduser', 'opted_into_sms')
    # ### end Alembic commands ###
