"""User opt in

Revision ID: c2184b22a0df
Revises: b552fc6476cd
Create Date: 2024-01-14 21:47:45.972804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c2184b22a0df'
down_revision: Union[str, None] = 'b552fc6476cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authenticateduser', sa.Column('opted_into_sms', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authenticateduser', 'opted_into_sms')
    # ### end Alembic commands ###
