# dialect+driver://username:password@host:port/database
# The "+" should be included in the driver env variable below
database:
  dialect: "postgresql"
  driver: ""
  port: 5432
  name: "sean_gpt"

minio:
  port: 443

kafka:
  brokers: >
    kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,
    kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092,
    kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092