# dialect+driver://username:password@host:port/database
# The "+" should be included in the driver env variable below
database:
  dialect: "postgresql"
  driver: ""
  port: 5432
  name: "sean_gpt"

minio:
  port: 9000