name: 'Docker Push Action'
description: 'Builds and pushes the backend Docker images to GHCR'
inputs:
  image-name:
    description: 'Name of the Docker image'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: '.'
  tag:
    description: 'Docker image tag'
    required: true
    default: 'latest'
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token }}

    - name: Determine the name of the latest wheel file
      id: get_wheel_file
      run: |
        echo $(python scripts/find_latest_whl.py dist)
        echo "wheel_file=$(python scripts/find_latest_whl.py dist)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build and Push Docker Image
      run: |
        docker build --platform=linux/amd64 --build-arg WHEEL_FILE="${{ steps.get_wheel_file.outputs.wheel_file }}" -t ${{ inputs.image-name }} -f ${{ inputs.dockerfile }} .
        docker tag ${{ inputs.image-name }} ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:${{ inputs.tag }}
        docker push ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:${{ inputs.tag }}
      shell: bash