name: 'Docker Push Action'
description: 'Builds and pushes the backend Docker images to GHCR'
inputs:
  image-name:
    description: 'Name of the Docker image'
    required: true
  tag:
    description: 'Docker image tag'
    required: true
    default: 'latest'
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ inputs.image-name }} .
        docker tag ${{ inputs.image-name }} ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:${{ inputs.tag }}
        docker push ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:${{ inputs.tag }}
      shell: bash
