apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
{{ if eq .Values.environment "local" }}
        imagePullPolicy: IfNotPresent
{{- end }}
        image: {{ .Values.seangpt.frontend_image.image_name }}:{{ .Values.seangpt.frontend_image.image_tag }}
        ports:
        - containerPort: 80
        env:
{{ if eq .Values.environment "local" }}
        - name: LAST_DEPLOYED
          value: "{{ now | unixEpoch }}"
{{- end }}
        - name: REACT_APP_API_ENDPOINT
          value: "{{ .Values.api_domain }}"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80