apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-seangpt
  annotations:
{{- if .Values.local }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
{{- else }}
    cert-manager.io/issuer: "letsencrypt-prod"
{{- end }}
spec:
{{- if not .Values.local }}
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: {{ .Values.cert_prefix }}-tls-cert
  - hosts:
    - {{ .Values.api_domain }}
    secretName: {{ .Values.cert_prefix }}-api-tls-cert
{{- end }}
  rules:
{{- if .Values.local }}
  - http:
{{- else }} 
  - host: {{ .Values.domain }}
    http:
{{- end }}
      paths:
      - path: /{{- if .Values.local }}static(/|$)(.*){{- end }}
        pathType: Prefix
        backend:
          service:
            name: sean-gpt-frontend
            port:
              number: 80
{{- if .Values.local }}
  - http:
{{- else }}
  - host: {{ .Values.api_domain }}
    http:
{{- end }}    
      paths:
      - path: /{{- if .Values.local }}api(/|$)(.*){{- end }}
        pathType: Prefix
        backend:
          service:
            name: sean-gpt
            port:
              number: 8000
  ingressClassName: nginx
