apiVersion: v1
kind: Secret
metadata:
  name: minio-user
  namespace: minio-tenant
type: Opaque
stringData:
  CONSOLE_ACCESS_KEY: {{ .Values.minio.access_key }}
  CONSOLE_SECRET_KEY: {{ .Values.minio.secret_key }}