apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - redis-cli -h localhost -p {{ .Values.redis.port }} ping
          initialDelaySeconds: 5
          periodSeconds: 5
        image: {{ .Values.redis.image }}
        volumeMounts:
        - name: redis-data
          mountPath: /data
        command:
          - redis-server
          - "--appendonly"
          - "yes"
          - "--dir"
          - "/data"
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.redis.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
