apiVersion: v1
kind: ConfigMap
metadata:
  name: sean-gpt-env
data:
{{- range $key, $value := .Values.env }}
  {{- if typeIs "map[string]interface {}" $value }}
    {{- range $subkey, $subvalue := $value }}
  {{ $key }}_{{ $subkey }}: {{ $subvalue | quote }}
    {{- end }}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}