apiVersion: apps/v1
kind: Deployment
metadata:
  name: sean-gpt-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sean-gpt-frontend
  template:
    metadata:
      labels:
        app: sean-gpt-frontend
    spec:
      containers:
      - name: sean-gpt-frontend
{{- if .Values.local }}
        imagePullPolicy: IfNotPresent
{{- end }}
        image: {{ .Values.sean_gpt_frontend.image }}
        ports:
        - containerPort: 80
        env:
        - name: LAST_DEPLOYED
          value: "{{ now | unixEpoch }}"
        - name: REACT_APP_API_ENDPOINT
          value: "{{ .Values.api_domain }}"

---

apiVersion: v1
kind: Service
metadata:
  name: sean-gpt-frontend
spec:
  selector:
    app: sean-gpt-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80