apiVersion: apps/v1
kind: Deployment
metadata:
  name: sean-gpt
spec:
  replicas: {{ .Values.sean_gpt.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: sean-gpt
  template:
    metadata:
      labels:
        app: sean-gpt
    spec:
      containers:
      - name: sean-gpt
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.sean_gpt.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        image: {{ .Values.sean_gpt.image }}
{{- if .Values.local }}
        imagePullPolicy: IfNotPresent
{{- end }}
        env:
        - name: LAST_DEPLOYED
          value: "{{ now | unixEpoch }}"
        envFrom:
        - prefix: "sean_gpt_"
          secretRef:
            name: sean-gpt-secrets
        - prefix: "sean_gpt_"
          configMapRef:
            name: sean-gpt-env
---
apiVersion: v1
kind: Service
metadata:
  name: sean-gpt
spec:
  type: ClusterIP
  selector:
    app: sean-gpt
  ports:
    - port: {{ .Values.sean_gpt.port }}
      targetPort: {{ .Values.sean_gpt.port }}