name: 'Test Baackend'
description: 'Run the backend pytest suite'

runs:
  using: 'composite'
  steps:
    - name: Setup Python environment
      uses: ./.github/actions/setup

    - name: Run tests
      run: |
        poetry run pytest
      shell: bash
