name: Test API

on:
  workflow_dispatch:
  pull_request:

jobs:      
  lint-api:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   

      - name: Setup dependencies
        uses: ./.github/actions/setup_dependencies
  
      #----------------------------------------------
      #          install and run linters
      #----------------------------------------------
      - run: cd sean_gpt && pylint sean_gpt tests

  test-api:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   

      - name: Setup dependencies
        uses: ./.github/actions/setup_dependencies

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: sean-gpt-local
  
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run tests
        run: |
          source .venv/bin/activate
          cd sean_gpt && poetry run pytest tests/
          coverage report
