name: Prepare for Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write
    
jobs:
  # Check also that TOML version matches the latest wheel
  # The wheel is located in the dist subfolder
  check-wheel-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   

      - uses: SebRollen/toml-action@v1.0.2
        id: read_toml
        with:
          file: 'pyproject.toml'
          field: 'tool.poetry.version'

      - name: Compare TOML version with latest wheel
        run: |
          version_toml=${{ steps.read_toml.outputs.value }}
          wheel_files=$(ls dist/*.whl)
          if [[ ! $wheel_files =~ $version_toml ]]; then
            echo "The version in pyproject.toml ($version_toml) does not match any wheel file."
            exit 1
          fi

  check-unique-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   

      - uses: SebRollen/toml-action@v1.0.2
        id: read_toml
        with:
          file: 'pyproject.toml'
          field: 'tool.poetry.version'

      - name: Fetch Tags from Main Branch
        run: git fetch --tags origin main

      - name: Check for Matching Tag on Main
        run: |
          version_tag="v${{ steps.read_toml.outputs.value }}"
          if git rev-parse "refs/tags/$version_tag" >/dev/null 2>&1; then
            echo "The version tag ($version_tag) already exists on the main branch."
            exit 1
          fi