name: Deploy to Production

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  packages: write
  contents: write
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get latest release tag
      id: get-latest-release
      run: |
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
        LATEST_TAG=$(echo $LATEST_RELEASE | jq -r .tag_name)
        echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

    - name: Checkout code at release tag
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.get-latest-release.outputs.tag }}
  
    - name: Configure Kubernetes context
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare for Deployment
      run: ./scripts/prepare_prod.sh

    - uses: helmfile/helmfile-action@v1.0.0
      with:
        helmfile-version: 'v0.160.0'
        helm-version: 'v3.13.3'
        helmfile-args: sync --environment prod
