name: Deploy

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  packages: write
  contents: write
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get latest release tag
      id: get-latest-release
      run: |
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
        LATEST_TAG=$(echo $LATEST_RELEASE | jq -r .tag_name)
        echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

    - name: Checkout code at release tag
      uses: actions/checkout@v2
      # with:
      #   ref: ${{ steps.get-latest-release.outputs.tag }}
  
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Build the frontend
      run: echo "TODO- Build the frontend"

    - name: Move the compiled frontend to the serving directory
      run: echo "TODO- Move the compiled frontend to the serving directory"

    - name: Build and push backend Docker image (this version)
      uses: ./.github/actions/build_push_docker
      with:
          image-name: 'sean_gpt'
          tag: ${{ steps.get-latest-release.outputs.tag }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push backend Docker image (latest)
      uses: ./.github/actions/build_push_docker
      with:
          image-name: 'sean_gpt'
          tag: 'latest'
          github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure Kubernetes context
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Create secrets.yaml file
      run: |
        echo "${{ secrets.secrets_yaml }}" > sean_gpt_chart/secrets.yaml

    - name: Deploy to kubernetes using helm
      run: |
        cd sean_gpt_chart
        helm upgrade --install seangpt-stable . -f secrets.yaml --namespace stable

