name: Deploy

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Configure Kubernetes context
      run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Build the frontend
      run: # TODO

    - name: Build and push backend Docker image
      uses: ./.github/actions/build_push_docker
      with:
          image-name: 'sean_gpt_backend'
          tag: 'latest'

    - name: Deploy to kubernetes (secrets, database, backend, and frontend)
      run: # TODO