name: Deploy

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Configure Kubernetes context
      run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Build the frontend
      run: echo "TODO- Build the frontend"

    - name: Move the compiled frontend to the serving directory
      run: echo "TODO- Move the compiled frontend to the serving directory"

    - name: Build and push backend Docker image
      uses: ./.github/actions/build_push_docker
      with:
          image-name: 'sean_gpt_backend'
          tag: ${{ github.ref }}

    - name: Deploy to kubernetes (secrets, database, backend, and frontend)
      run: echo "TODO"