name: Prepare for Development Merge

on:
  workflow_dispatch:
  pull_request:
    branches:
      - development

permissions:
  contents: write
    
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: test-backend
        uses: ./.github/actions/test-backend
