name: Prepare for Development Merge

on:
  workflow_dispatch:
  pull_request:
    branches:
      - development

permissions:
  contents: write
    
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   

      - name: test-backend
        uses: ./.github/actions/test-backend
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ADMIN_PHONE: ${{ secrets.ADMIN_PHONE }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          API_DB_USER: ${{ secrets.API_DB_USER }}
          API_DB_PASSWORD: ${{ secrets.API_DB_PASSWORD }}
          TWILIO_TEST_SID: ${{ secrets.TWILIO_TEST_SID }}
          TWILIO_TEST_AUTH_TOKEN: ${{ secrets.TWILIO_TEST_AUTH_TOKEN }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
  
          API_DB_HOST: localhost
          REDIS_HOST: localhost
          DEBUG: "True"
  