name: Prepare for Development Merge

on:
  workflow_dispatch:
  pull_request:
    branches:
      - development

permissions:
  contents: write
    
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   

      - name: test-backend
        uses: ./.github/actions/test-backend

  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   

      - name: lint-backend
        uses: ./.github/actions/lint-backend
