name: Prepare for Release

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
    
jobs:
  process-version:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   

      - name: Extract Version from pyproject.toml
        id: extract-version
        uses: ./.github/actions/retrieve_version
        with:
          pyproject-path: 'pyproject.toml'

      - name: Fetch Tags from Main Branch
        run: git fetch --tags origin main

      - name: Check for Matching Tag on Main
        run: |
          version_tag="v${{ steps.extract-version.outputs.version }}"
          if git rev-parse "refs/tags/$version_tag" >/dev/null 2>&1; then
            echo "The version tag ($version_tag) already exists on the main branch."
            exit 1
          fi

      - name: Setup Python environment
        uses: ./.github/actions/setup
  
      - name: Build Package
        run: poetry build

      - name: Check for Auto-Commit
        id: check_autocommit
        run: |
          if git log -1 --pretty=%B | grep -q "Build package for version"; then
            echo "This commit was made by the workflow. Skipping push to prevent recursion."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Changes
        if: steps.check_autocommit.outputs.skip == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Build package for version ${{ steps.extract-version.outputs.version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
