name: Create a Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: SebRollen/toml-action@v1.0.2
        id: read_toml
        with:
          file: 'pyproject.toml'
          field: 'tool.poetry.version'
  
      - name: Create Tag
        run: |
          version_tag="v${{ steps.read_toml.outputs.value }}"
          git tag $version_tag
          git push origin $version_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PR Description and Write to File
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            fs.writeFileSync('pr_description.md', pr.data.body);
                  
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: "v${{ steps.extract-version.outputs.version }}"
          release_name: "Release v${{ steps.extract-version.outputs.version }}"
          body_path: pr_description.md
          draft: false
          prerelease: false
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/sean_gpt-${{ steps.read_toml.outputs.value }}-py3-none-any.whl
          asset_name: sean_gpt-${{ steps.read_toml.outputs.value }}-py3-none-any.whl
          asset_content_type: application/octet-stream
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/sean_gpt-${{ steps.read_toml.outputs.value }}.tar.gz
          asset_name: sean_gpt-${{ steps.read_toml.outputs.value }}.tar.gz
          asset_content_type: application/octet-stream

  merge-main-into-development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   

      - name: Merge main into development
        run: |
          git fetch origin
          git checkout development
          git merge origin/main
          git push origin development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      