name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python environment
      uses: ./.github/actions/setup

    - name: Run tests
      run: |
        poetry run pytest
