name: Lint Code

on:
  pull_request:
    branches: [ main, development ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python environment
      uses: ./.github/actions/setup

    - name: Run linter
      run: |
        poetry run pylint sean_gpt tests