name: PR Tagging and Version Checking

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  process-version:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Extract Version from pyproject.toml
        id: extract-version
        uses: ./.github/actions/retrieve_version
        with:
          pyproject-path: 'pyproject.toml'

      - name: Apply Tag to Latest PR Commit
        run: |
          version_tag="v${{ steps.extract-version.outputs.version }}"
          git tag $version_tag
          git push origin $version_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Tags from Main Branch
        run: git fetch --tags origin main

      - name: Check for Matching Tag on Main
        run: |
          version_tag="v${{ steps.extract-version.outputs.version }}"
          if git rev-parse "refs/tags/$version_tag" >/dev/null 2>&1; then
            echo "The version tag ($version_tag) already exists on the main branch."
            exit 1
          fi
